### ISSUE TITLE
Wisp gets despawned on weapon switch. 

### ISSUE THREAD

**Issue by Onins** [shudnal/CircletExtended#1]
Issue happens during switching of weapons or sheathing and unsheathing. Temporary workaround is to use flash (T) to release the wisp every weapons switch.

**Comment by shudnal** [comment]
Sadly I had no luck reproducing it. For me wisp stays no matter I do. Maybe there is some incompatibility with mods like "use equipment in water", "use weapons in water".  Maybe some mod affecting status effects.
Of mods like this I use only https://thunderstore.io/c/valheim/p/Azumatt/Queue_Me_Maybe/ and it works fine.

**Comment by Onins** [comment]
This might be a mod conflict. Anyway thanks for checking it out
