### ISSUE TITLE
Circlet level1 would go in head slot instead of circlet slot

### ISSUE THREAD

**Issue by sighsorry1029** [shudnal/CircletExtended#2]
Hello, recently I have tried extra slot and circlet extended and I have enabled config option for circlet's slot. And circlet level 2,3,4 would go in circlet slot but circlet level 1 would go in head slot. 
Thank you for the mods you made. I think I can replace several mods with only extra slot mod

https://github.com/user-attachments/assets/712a4ce0-c01f-438d-bcd2-7df5ea9d7bf1

**Comment by sighsorry1029** [comment]
Uploading Untitled video - Made with Clipchamp (2).mp4…

**Comment by shudnal** [comment]
This is intended part of circlet features progression if you have config value "Get features by circlet upgrade" enabled. I guess I should make it more clear in mod's description.

**Comment by sighsorry1029** [comment]
> This is intended part of circlet features progression if you have config value "Get features by circlet upgrade" enabled. I guess I should make it more clear in mod's description.
Oh, I didn't know that. Thank you for the reply.
